import { describe, it, expect } from "vitest";
import { loadContent, type ContentModule } from "./content";

interface TestItem {
	slug: string;
	title: string;
	date?: string;
	type?: string;
	publishedAt?: string;
}

describe("loadContent", () => {
	const mockModules: Record<string, ContentModule<TestItem>> = {
		"/src/content/test/item-1.md": {
			metadata: { slug: "item-1", title: "Item 1", publishedAt: "2025-01-01" },
			default: "Component1"
		},
		"/src/content/test/item-2.md": {
			metadata: { slug: "item-2", title: "Item 2", publishedAt: "2025-01-02" },
			default: "Component2"
		},
		"/src/content/test/_draft.md": {
			metadata: { slug: "draft", title: "Draft", publishedAt: "2025-01-03" },
			default: "ComponentDraft"
		}
	};

	it("loads content from modules", () => {
		const result = loadContent(mockModules);
		expect(result).toHaveLength(2); // Should exclude _draft
		expect(result[0].title).toBe("Item 2"); // Default sort by date desc
		expect(result[1].title).toBe("Item 1");
	});

	it("ignores files starting with underscore", () => {
		const result = loadContent(mockModules);
		expect(result.find((i) => i.slug === "draft")).toBeUndefined();
	});

	it("extracts slug from path if missing in metadata", () => {
		const modules = {
			"/src/content/test/autogenerated-slug.md": {
				metadata: { title: "Auto Slug" } as TestItem,
				default: null
			}
		};
		const result = loadContent(modules);
		expect(result[0].slug).toBe("autogenerated-slug");
	});

	it("uses custom slugFromPath option", () => {
		const modules = {
			"/complex/path/123-custom.md": {
				metadata: { title: "Custom" } as TestItem,
				default: null
			}
		};
		const result = loadContent(modules, {
			slugFromPath: (path) => path.split("-")[1].replace(".md", "")
		});
		expect(result[0].slug).toBe("custom");
	});

	it("injects type from path", () => {
		const modules = {
			"/src/content/posts/item.md": {
				metadata: { slug: "s", title: "T" } as TestItem,
				default: null
			}
		};
		const result = loadContent(modules, {
			typeFromPath: () => "post"
		});
		expect(result[0].type).toBe("post");
	});

	it("filters items", () => {
		const result = loadContent(mockModules, {
			filter: (item) => item.slug === "item-1"
		});
		expect(result).toHaveLength(1);
		expect(result[0].slug).toBe("item-1");
	});

	it("sorts items (custom sort)", () => {
		const result = loadContent(mockModules, {
			sort: (a, b) => a.title.localeCompare(b.title) // Ascending
		});
		expect(result[0].title).toBe("Item 1");
		expect(result[1].title).toBe("Item 2");
	});

	it("skips modules without metadata", () => {
		const badModules = {
			"/bad.md": {
				default: "No metadata"
			}
		} as unknown as Record<string, ContentModule<TestItem>>;
		
		const result = loadContent(badModules);
		expect(result).toHaveLength(0);
	});
});
